app = "coinupdater-bot"
primary_region = "atl"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

app = "coinupdater-bot"
primary_region = "atl"

[build]
  buildpacks = ["heroku/python"]
  
[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
